THRIFT-4809: Implement episodic compilation for js code generation
mustafa-cosar/thrift pull request #1
Opened 2019-03-11 09:13 UTC by mustafa-cosar

Implement episodic compilation for js code generation

Two new options are:
`thrift_package_output_directory`: If set, the generator will create an episode file `thrift.js.episode` that will contain the import paths of the generated modules. `thrift_package_output_directory` will be a prefix for the import path

`imports`: The `:` separated paths of node_modules to import from. The node_module must have `thrift.js.episode` file in the module root. This option is mutually exclusive with `-recurse` option.

2019-03-11 09:55 UTC, thehcma requested changes

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +  void parse_imports(t_program* program, const std::string imports_string);
...string&

in both cases

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +  vector<string> imports;
use std:: (or not) consistently

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +  vector<string> imports;
seems like we shouldn't be using it

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    string f_episode_file_path = outdir + episode_file_name;
auto const

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    string types_module = program_->get_name() + "_types";
same

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    f_episode_ << service_name_ + ":" + thrift_package_output_directory_ + "/" + service_name_ << endl;
use << instead of string concatenation

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "[-gen js:imports=] option is not usable in recursive generation mode";
..._code_ generation...

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    imports.push_back(import);
emplace_back

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "Invalid usage: [-gen js:imports=] requires at least one path (multiple paths are separated by ':', "
make sure the exception start with uppercase/lowercase consistently

also if paths must be absolute - let's do a separate validation with a separate error message

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    if (import.empty()) {
we just validated that above

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +        throw "the episode file '" + episode_file_path + "' is malformed";
add details here saying what we expect

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +      if (module_name.size() == 0 || import_path.size() == 0) {
let's split this validation into two

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +        throw "Multiple providers found for " + module_name + "\n\t" + module_import_path + "\n\t" + result.first->second;
providers of what?

let's add both of the providers to the output error message

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +      const auto module_import_path = import.substr(import.find_last_of('/') + 1) + "/" + import_path;
can this ``find_last_of`` fail?

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "empty thrift_package_output_directory values are invalid";
the triftt_package_output_directory argument must not be empty

btw, check the other functions and make sure that failures are not typed exceptions (I find this particularly ugly here)

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "empty thrift_package_output_directory values are invalid";
see error message improvement above

2019-03-11 09:55 UTC, thehcma commented on compiler/cpp/src/thrift/parse/t_program.h
> +  void set_recursive(bool recursive) { recursive_ = recursive; }
const

2019-03-11 12:41 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +  void parse_imports(t_program* program, const std::string imports_string);
fixed

2019-03-11 12:41 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +  vector<string> imports;
fixed

2019-03-11 12:48 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "[-gen js:imports=] option is not usable in recursive generation mode";
fixed

2019-03-11 12:48 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    imports.push_back(import);
fixed

2019-03-11 13:01 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    if (import.empty()) {
fixed

2019-03-11 13:02 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "Invalid usage: [-gen js:imports=] requires at least one path (multiple paths are separated by ':', "
fixed

2019-03-11 13:16 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +        throw "the episode file '" + episode_file_path + "' is malformed";
fixed

2019-03-11 13:19 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +      if (module_name.size() == 0 || import_path.size() == 0) {
fixed

2019-03-11 13:20 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "empty thrift_package_output_directory values are invalid";
fixed

2019-03-11 13:21 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    throw "empty thrift_package_output_directory values are invalid";
fixed

2019-03-11 13:21 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/parse/t_program.h
> +  void set_recursive(bool recursive) { recursive_ = recursive; }
fixed

2019-03-11 13:23 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    f_episode_ << service_name_ + ":" + thrift_package_output_directory_ + "/" + service_name_ << endl;
fixed

2019-03-11 13:24 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    string f_episode_file_path = outdir + episode_file_name;
fixed

2019-03-11 13:24 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +    string types_module = program_->get_name() + "_types";
fixed

2019-03-11 13:28 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +      const auto module_import_path = import.substr(import.find_last_of('/') + 1) + "/" + import_path;
No, it returns max `size_t` if it cannot find the character. Adding 1 to it makes it overflow to 0 and we get the whole string, which is what we want in case there is no `/`

We strip a `/` above so it shouldn't be found at the end unless the user enters `foo//`

2019-03-11 13:42 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/generate/t_js_generator.cc
> +        throw "Multiple providers found for " + module_name + "\n\t" + module_import_path + "\n\t" + result.first->second;
fixed

2019-03-13 09:09 UTC, thehcma approved these changes

2019-03-13 09:09 UTC, thehcma commented on compiler/cpp/src/thrift/parse/t_program.h
> +  const bool& get_recursive() const { return recursive_; }
no need for reference here (the reference is more expensive than the copy)

2019-03-13 09:09 UTC, thehcma commented on lib/nodejs/test/episodic-code-generation-test/client.js
> +  .option("--host <host>", "Set thrift server host to connect", "localhost")
Set the Thrift server...

2019-03-13 09:09 UTC, thehcma commented on lib/nodejs/test/episodic-code-generation-test/client.js
> +  .option("--port <port>", "Set thrift server port number to connect", 9090)
same

2019-03-13 09:09 UTC, thehcma commented on lib/nodejs/test/testAll.sh
> +# generating thrift code
Thrift

2019-03-13 09:09 UTC, thehcma commented on lib/nodejs/test/testAll.sh
> +cp --force ${DIR}/episodic_compilation.package.json ${DIR}/episodic-code-generation-test/node_modules/types-package/package.json
perhaps you can put the common directories in a variable, so it's easier to follow and minimizes the chances of a typo (e.g., the Thrift compiler path, the destination dirs, etc)

2019-03-13 09:09 UTC, thehcma commented on lib/nodejs/test/episodic-code-generation-test/client.js
> +const Service = require("./gen-2/second-episode/gen-nodejs/Service");
did you check if the file is not emitted, whether it will trigger a visible failure? (I suppose during the runtime)

2019-03-13 09:15 UTC, mustafa-cosar commented on compiler/cpp/src/thrift/parse/t_program.h
> +  const bool& get_recursive() const { return recursive_; }
fixed

2019-03-13 09:16 UTC, mustafa-cosar commented on lib/nodejs/test/episodic-code-generation-test/client.js
> +  .option("--host <host>", "Set thrift server host to connect", "localhost")
fixed

2019-03-13 09:16 UTC, mustafa-cosar commented on lib/nodejs/test/episodic-code-generation-test/client.js
> +  .option("--port <port>", "Set thrift server port number to connect", 9090)
fixed

2019-03-13 09:17 UTC, mustafa-cosar commented on lib/nodejs/test/testAll.sh
> +# generating thrift code
fixed

2019-03-13 09:18 UTC, mustafa-cosar commented on lib/nodejs/test/episodic-code-generation-test/client.js
> +const Service = require("./gen-2/second-episode/gen-nodejs/Service");
Yes, it fails during the runtime if the file is not generated.

2019-03-13 09:38 UTC, mustafa-cosar commented on lib/nodejs/test/testAll.sh
> +cp --force ${DIR}/episodic_compilation.package.json ${DIR}/episodic-code-generation-test/node_modules/types-package/package.json
improved

2019-03-13 09:50 UTC, closed without merging